yarnPath: .yarn/releases/yarn-3.5.0.cjs

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAlwaysAuth: true
    npmAuthToken: 74BF9580-6A40-4C4E-ABEE-33976F854B74
