export const Common = {
  Help: "Help",
  Save: "Save",
  Saving: "Saving",
  Cancel: "Cancel",
  Name: "Name",
  Create: "Create",
  Creating: "Creating",
  Desc: "Description",
  Email: "Email",
  Username: "Username",
  Password: "Password",
  ConfirmPassword: "Confirm Password",
  AppName: "PersonaVerse",
  Edit: "Edit",
} as const;
